language: python
python:
  - "2.7"
  - "3.4"

notifications:
  email: false

install:
  - git submodule update --init --recursive
  - python setup.py install --user

script:
   - nosetests -s -v tests/
